config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#top'
  get 'players/new'
  post 'players' => 'players#create'
  get 'players' => 'players#index'
  get 'players/:id' => 'players#show', as: 'player'
  get 'players/:id/edit' => 'players#edit', as: 'edit_player'
  patch 'players/:id' => 'players#update', as: 'update_player'
  delete 'players/:id' => 'players#destroy', as: 'destroy_player'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  attachment :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  def new
    @player = Player.new
  end
  
  def create
    @player = Player.new(player_params)
    @player.save
    redirect_to player_path(@player.id)
  end
  
  def index
    @players = Player.page(params[:page]).reverse_order
  end
  
  def show
    @player = Player.find(params[:id])
  end
  
  def edit
    @player = Player.find(params[:id])
  end
  
  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    redirect_to player_path(@player.id)
  end
  
  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to players_path
  end
  
  private
  
  def player_params
    params.require(:player).permit(:name, :age, :team, :nationality, :position, :image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/homes/top.html.erb
<div id="container">
  <div id="slideshow">
    <div class="image1"></div>
    <div class="image2"></div>
    <div class="image3"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootballPlayersApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/0daeb9e6e6.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1 class="headline"><i class="far fa-futbol"></i> Football Players <i class="fas fa-running"></i></h1>
    </header>
    <nav>
      <ul class="nav-list">
        <li class="nav-list-item">
          <i class="fas fa-home"></i> 
          <%= link_to " Top", root_path %>
        </li>
        <li class="nav-list-item">
          <i class="fas fa-running"></i> 
          <%= link_to "Players", players_path %>
        </li>
        <li class="nav-list-item">
          <i class="fas fa-plus"></i> 
          <%= link_to "New Player", players_new_path %>
        </li>
      </ul>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/players/edit.html.erb
<h1><i class="fas fa-edit"></i> Edit Player</h1>
<%= form_for(@player, url: "/players/#{@player.id}") do |f| %>
  <h4 class="model">Name</h4>
  <%= f.text_field :name %>
  <h4 class="model">Age</h4>
  <%= f.number_field :age %>
  <h4 class="model">Team</h4>
  <%= f.text_field :team, min:16, max:60 %>
  <h4 class="model">Nationality</h4>
  <%= f.text_field :nationality %>
  <h4 class="model">Position</h4>
  <%= f.select :position, ['FW','MF','DF','GK'],{include_blank:'Please select'} %>
  <br>
  <%= f.submit 'Edit', class:"btn btn-success" %>
<% end %>

app/views/players/index.html.erb
<h1 class="headline"><i class="fas fa-running"></i>  Player List</h1>
<% @players.each do |player| %>
  <div class="player-box">
    <%= attachment_image_tag player, :image, :fill, 200, 200, format: 'jpeg', class:"player-image" %>
    <div class="player-information">
      <span class="player-name"><%= link_to player.name, player_path(player.id) %></span>
      <span class="player-team"><%= player.team %></span>
    </div>
  </div>
<% end %>
<%= paginate @players %>

app/views/players/new.html.erb
<h1>New Player</h1>
<%= form_for(@player, url: '/players') do |f| %>
  <h4 class="model">Name</h4>
  <%= f.text_field :name %>
  <h4 class="model">Image</h4>
  <%= f.attachment_field :image %>
  <h4 class="model">Age</h4>
  <%= f.number_field :age %>
  <h4 class="model">Team</h4>
  <%= f.text_field :team, min:16, max:60 %>
  <h4 class="model">Nationality</h4>
  <%= f.text_field :nationality %>
  <h4 class="model">Position</h4>
  <%= f.select :position, ['FW','MF','DF','GK'],{include_blank:'Please select'} %>
  <br>
  <%= f.submit 'Post', class:"btn btn-success" %>
<% end %>

app/views/players/show.html.erb
<div class="container">
  <div class="row">
    <div class="left-content col-md-6 col-xs-12">
      <p class="model">Name</p>
      <h2><%= @player.name %></h2>
      <p class="model">Image</p>
      <%= attachment_image_tag @player, :image, :fill, 300, 300, format: 'jpeg', class:"player-image" %>
    </div>
    <div class="right-content col-md-6 col-xs-12">
      <p class="model">Age</p>
      <h2><%= @player.age %></h2>
      <p class="model">Team</p>
      <h2><%= @player.team %></h2>
      <p class="model">Nationality</p>
      <h2><%= @player.nationality %></h2>
      <p class="model">Position</p>
      <h2><%= @player.position %></h2>
      <br>
      <i class="fas fa-edit"></i><%= link_to " Edit", edit_player_path(@player.id), class:"action" %>
      <i class="fas fa-trash-alt"></i><%= link_to "Delete", destroy_player_path(@player.id), method: :delete, "data-confirm" => "本当に消しますか？", class:"action" %>
    </div>
  </div>
</div>